<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Gowtham-PL" ignored="0" name="case1" tests="6" failures="1" timestamp="2023-04-06T00:35:22 IST" time="0.281" errors="0">
  <testcase name="case1" time="0.016" classname="reRunFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- case1 -->
  <testcase name="case2" time="0.016" classname="reRunFailedTestCases.TestCases"/>
  <testcase name="case1" time="0.0" classname="reRunFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- case1 -->
  <testcase name="case1" time="0.0" classname="reRunFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- case1 -->
  <testcase name="case1" time="0.0" classname="reRunFailedTestCases.TestCases">
    <skipped/>
  </testcase> <!-- case1 -->
  <testcase name="case1" time="0.0" classname="reRunFailedTestCases.TestCases">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at reRunFailedTestCases.TestCases.case1(TestCases.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- case1 -->
</testsuite> <!-- case1 -->
